### ISSUE TITLE
small changes needed to make mook-state-checker work (again?) in roll20

### ISSUE THREAD

**Issue by uhu79** [Heilemann/roll20-tor-scripts#2]
I just set up my roll20 campaign and this script did not work

I found that line 33 should be
on('change:graphic:bar2_value', function(token) {
previously it was bar1 which is endurance being changed, doesn't make sense right?

and line 46
    if (hate === '0') {
was === 0 but obviously roll20 charsheet does not have an integer but a string value in the bar, so this if never was true, with the '0' it works

**Comment by Heilemann** [comment]
In which file?

**Comment by Heilemann** [comment]
Pushed a change just now, which should fix it.
