### ISSUE TITLE
state checker issues

### ISSUE THREAD

**Issue by uhu79** [Heilemann/roll20-tor-scripts#3]
besides the mook checker, also the state checker for the PCs stopped working, maybe something changed?

if you look at total_fatigue attribute it's not a value but a string like this "0 + 1 + 2 + 0 + 0 +0 +1+2+0" and that's the issue I guess

**Comment by Heilemann** [comment]
You see that on the mook charsheet?

**Comment by uhu79** [comment]
no it's not for mooks - the one for the player chars, the state checker. and I sent the total_fatigue attribute to chat via macro and there I see the full string but not the calculated value
the charsheet (pc) shows the result though... confusing.

**Comment by uhu79** [comment]
I just thought that if you use the new possibilities that the Sheet Worker scripts https://wiki.roll20.net/Sheet_Worker_Scripts give you, you could do the auto-setting of 'weary' and 'miserable' on the sheet and use the API script only to set the tint etc.
would that be a more efficient way to achieve it? on the other hand how to deal with temp-miserable and temp-weary states, the script would override this - I have very limited skills in scripting (it's 13 years ago that I had to do coding...)

**Comment by uhu79** [comment]
and I just saw in the readme that there once was a tor-fatigue.js that was doing the calculation. seems like you changed that.

**Comment by uhu79** [comment]
maybe... the disabled="disabled" value in the sheet is the issue, it might set encumbrance_fatigue to string instead of integer?

**Comment by uhu79** [comment]
I now got the wounded-part to work (again you need to manually create the attributes "wounded" and "wound_treated" in each character sheet.
I wonder now what the part with the yellow bubble is about - it seems the wound just replaces yellow with red in case a wound or treated wound occurs. Did you treat those two differently in the past?

still struggling with fatigue, though

**Comment by Heilemann** [comment]
I haven't used these scripts for about a year, when we switched over to playing Trail of Cthulhu instead, so I'm a bit out of the loop (ToC doesn't have a lot of demands re. scripting).

Can you attach some screenshots for more context?

**Comment by uhu79** [comment]
this part is checking if a char is wounded or has a treated wound, right? it then gives it a red dot on the token. that works fine. the script also talks about a yellow dot to set to false in any case. I wonder where that came from. maybe you did weary with a yellow dot and changed it to the tinted mode later? not sure what screenshots could be helpful

 if (
        (wounded && parseInt(wounded, 10) !== 0) ||
        (wound_treated && parseInt(wound_treated, 10) !== 0)
    ) {
        tokens.forEach(function(token) {
            token.set('status_yellow', false);
            // #98000
            token.set('status_red', '');
        }, this);
    } else {
        tokens.forEach(function(token) {
            token.set('status_yellow', false);
            // transparent
            token.set('status_red', false);
        }, this);
    }

**Comment by uhu79** [comment]
I am working on the fatigue checker and will post an update later, I have developed some understanding now.
